language: python
python: 3.7

#  Not needed when used with elasticbeanstalk
#services:
#  - docker

#branches:
#  only:
#  - master
#  - dev

env:
  - deploy_mode=prod

script:
  - ./shell_scripts/test.sh

#  Not needed when used with elasticbeanstalk
#after_success:
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_URL
#  - docker-compose build
#  # Push to repo
#  - docker-compose push

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "eu-west-1"
  app: "cicdtraining"
  env: "cicdtraining-dev"
  bucket_name: "mob-cicd-training"