language: python
python: 3.7

services:
  - docker

#branches:
#  only:
#  - master
#  - dev

script:
  - ./test.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_URL
  - docker-compose build
  # Push to repo
  - docker-compose push