version: '3'
services:
  webserver:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    image: 859523592427.dkr.ecr.us-east-1.amazonaws.com/cicdtraining:latest
    volumes:
    - ".:/modelserver/code_volume/:ro"
