branch-defaults:
  master:
    environment: cicdtraining-dev
    group_suffix: null
global:
  application_name: cicdtraining
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.09.9-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
